/*
 * NBA Doha hotspot data
 * Generated by manager.html
 */
const hotspots = [
  {
    number: "1",
    title: "NBA Fan Zone",
    shortLabel: "Fan Zone",
    category: "Experience",
    filterCategory: "experience",
    description: "Music, entertainment, basketball challenges and special guest appearances throughout the event.",
    time: "September 1st - 3rd",
    coordinates: [51.532200, 25.286700],
    buttonLabel: "View programme",
    link: "#"
  },
  {
    number: "2",
    title: "The Gate Mall",
    shortLabel: "The Gate Mall",
    category: "Mall",
    filterCategory: "retail",
    description: "Come see what's on offer at The Gate Mall",
    time: "Open Friday 1st - Tuesday 5th September",
    coordinates: [51.526842, 25.323639],
    buttonLabel: "See activity",
    link: "#"
  },
  {
    number: "3",
    title: "NBA Store",
    shortLabel: "NBA Store",
    category: "Merchandise",
    filterCategory: "retail",
    description: "Shop jerseys, apparel, accessories and event-exclusive products.",
    time: "Open until 10:00 PM",
    coordinates: [51.541000, 25.282500],
    buttonLabel: "Explore store",
    link: "#"
  },
  {
    number: "4",
    title: "Food Court",
    shortLabel: "Food Court",
    category: "Food and drink",
    filterCategory: "food",
    description: "Discover a selection of local favourites and international food options.",
    time: "Open throughout the event",
    coordinates: [51.536000, 25.278000],
    buttonLabel: "View food options",
    link: "#"
  },
  {
    number: "5",
    title: "Al Asmakh Mall",
    shortLabel: "Al Asmakh Mall",
    category: "Shopping Mall",
    filterCategory: "retail",
    description: "Come see what's on offer at Al Asmakh Mall",
    time: "Open throughout September",
    coordinates: [51.496209, 25.282586],
    buttonLabel: "View mall",
    link: "https://www.centrepointstores.com/qa/en"
  },
  {
    number: "6",
    title: "Larissa Restaurant",
    shortLabel: "Larissa Restaurant",
    category: "Food and Drink",
    filterCategory: "food",
    description: "Try some delicious food at Larissa Restaurant!",
    time: "Open all day every day",
    coordinates: [51.497273, 25.307632],
    buttonLabel: "See menu",
    link: "https://blank"
  },
  {
    number: "7",
    title: "Hamad Medical City",
    shortLabel: "Hospital",
    category: "Other",
    filterCategory: "other",
    description: "Here is a hospital on the map",
    time: "Open 24/7",
    coordinates: [51.502272, 25.292818],
    buttonLabel: "More info",
    link: "#"
  },
  {
    number: "8",
    title: "Grand Hamad Stadium",
    shortLabel: "Stadium",
    category: "Experience",
    filterCategory: "experience",
    description: "This is a description for Grand Hamad Stadium",
    time: "Match days only",
    coordinates: [51.520012, 25.258482],
    buttonLabel: "More info",
    link: "#"
  }
];
